FROM ubuntu:16.04

MAINTAINER Cat.1 "zhuyuefeng0@gmail.com"

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
RUN echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list

RUN apt-get update
RUN apt-get install -y mongodb-org
RUN mkdir -p /data/db


EXPOSE 27017

CMD mongod
